<a href="https://colab.research.google.com/github/gameqube963741/Tensorflow_demo/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Flatten, Dense, Dropout
import matplotlib.pyplot as plt

def run():
    ds = tf.keras.datasets.mnist

    (train_x, train_y), (test_x, test_y) = ds.load_data()
    print("train_x.shape:", train_x.shape, ", train_y.shape:", train_y.shape)
    print("test_x.shape:", test_x.shape, ", test_y.shape:", test_y.shape)

    # 正規化
    train_x = tf.keras.utils.normalize(train_x)
    test_x = tf.keras.utils.normalize(test_x)

    # one-hot
    train_y = tf.keras.utils.to_categorical(train_y)
    test_y = tf.keras.utils.to_categorical(test_y)
    print("train_y.shape:", train_y.shape, ", test_y.shape:", test_y.shape)

    model = tf.keras.Sequential()

    # 模型定義
    model.add(Flatten(input_shape=[28, 28]))
    model.add(Dense(1000, activation="relu"))
    model.add(Dense(10, activation="softmax"))

    # 模型概要
    model.summary()

    # 編譯模型
    model.compile(
        loss=tf.keras.losses.categorical_crossentropy,
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        metrics=["accuracy"]
    )

    # 訓練模型參數
    history = model.fit(train_x, train_y, validation_data=(
        test_x, test_y), epochs=1, batch_size=128)

    score = model.evaluate(test_x, test_y, batch_size=128)
    print('訓練評價分數: ', score)

    result = model.predict(test_x, batch_size=128)
    print('原始值 :', np.argmax(test_y[:20], axis=1))
    print('預測值 :', np.argmax(result[:20], axis=1))

run()

train_x.shape: (60000, 28, 28) , train_y.shape: (60000,)
test_x.shape: (10000, 28, 28) , test_y.shape: (10000,)
train_y.shape: (60000, 10) , test_y.shape: (10000, 10)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 1000)              785000    
_________________________________________________________________
dense_1 (Dense)              (None, 10)                10010     
Total params: 795,010
Trainable params: 795,010
Non-trainable params: 0
_________________________________________________________________
79/79 [==============================] - 0s 2ms/step - loss: 0.1461 - accuracy: 0.9577
訓練評價分數:  [0.14605768024921417, 0.9577000141143799]
原始值 : [7 2 1 0 4 1 4 9 5 9 0 6 9 0 1 5 9 7 3 4]
預測值 : [7 2 1 0 4 1 4 9 6 9 

# 實戰練習

In [2]:
# 公式
# f(x)=x^n

# 微分(求導數)：
# f'(x)=n*x^(n-1)

'''
ex:
y=x^2
微分(求導數)：
dy/dx=2x^(2-1)=2x
'''

import tensorflow as tf

x = tf.constant(10.)

with tf.GradientTape() as tape:
    tape.watch([x])
    y=x**2

dy_dx = tape.gradient(y, x)
print(dy_dx)
# 結果 >tf.Tensor(20.0, shape=(), dtype=float32)

tf.Tensor(20.0, shape=(), dtype=float32)


# 實戰2

In [3]:
import numpy as np
import pprint as pp
from tensorflow.keras.preprocessing.sequence import pad_sequences

comment1 = [1,2,3,4]
comment2 = [1,2,3,4,5,6,7]
comment3 = [1,2,3,4,5,6,7,8,9,10]

x_train = np.array([comment1, comment2, comment3], dtype=object)
print(), pp.pprint(x_train)

# 左邊補0，統一數組長度
x_test = pad_sequences(x_train)
print(), pp.pprint(x_test)

# 左邊補255，統一數組長度
x_test = pad_sequences(x_train, value=255)
print(), pp.pprint(x_test)

# 右邊補0，統一數組長度
x_test = pad_sequences(x_train, padding="post")
print(), pp.pprint(x_test)

# 切分數組，只保留後三位
x_test = pad_sequences(x_train, maxlen=3)
print(), pp.pprint(x_test)

# 切分數組，只保留前三位
x_test = pad_sequences(x_train, maxlen=3, truncating="post")
print(), pp.pprint(x_test)


array([list([1, 2, 3, 4]), list([1, 2, 3, 4, 5, 6, 7]),
       list([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])], dtype=object)

array([[ 0,  0,  0,  0,  0,  0,  1,  2,  3,  4],
       [ 0,  0,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int32)

array([[255, 255, 255, 255, 255, 255,   1,   2,   3,   4],
       [255, 255, 255,   1,   2,   3,   4,   5,   6,   7],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]], dtype=int32)

array([[ 1,  2,  3,  4,  0,  0,  0,  0,  0,  0],
       [ 1,  2,  3,  4,  5,  6,  7,  0,  0,  0],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int32)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]], dtype=int32)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)


(None, None)

# 定義變量 與 常量

In [4]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.system('cls')

import tensorflow as tf

In [5]:
# 定義變量
a = tf.Variable(1)
b = tf.Variable(1.)
c = tf.Variable([1.])
d = tf.Variable(1., dtype=tf.float32)

print("-" * 40)
print(a)
print(b)
print(c)
print(d)

# print(a+b)  # error:類型不匹配
print(b+c)    # Tensor類型
print(b+c[0]) # Tensor類型

----------------------------------------
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
tf.Tensor([2.], shape=(1,), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [6]:
# 定義Tensor
x1 = tf.constant(1)
x2 = tf.constant(1.)
x3 = tf.constant([1.])
x4 = tf.constant(1, dtype=tf.float32)

print('-' * 40)
print(x1)
print(x2)
print(x3)
print(x4)

print(x2+x3[0])

----------------------------------------
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor([1.], shape=(1,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)


# 定義變量時硬體的區別

In [7]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.system("cls")

import tensorflow as tf

################################
# 定義變量硬體
a = tf.Variable(1)
b = tf.Variable(10.)

print("-" * 40)
print("a.device:", a.device, a) # CPU
print("b.device:", b.device, b) # GPU

################################
# 定义Tensor后看设备
x1 = tf.constant(100)
x2 = tf.constant(1000.)

print("-" * 40)
print("x1.device:", x1.device, x1) # CPU
print("x2.device:", x2.device, x2) # CPU

################################
print("-" * 40)

# CPU+CPU
ax1 = a + x1
print("ax1.device:", ax1.device, ax1) # GPU

# CPU+GPU
bx2 = b + x2
print("bx2.device:", bx2.device, bx2) # GPU

################################
# 指定 GPU 定義 Tensor
gpu_a = tf.identity(a)
gpu_x1 = tf.identity(x1)

print("-" * 40)
print("gpu_a.device:", gpu_a.device, gpu_a)
print("gpu_x1.device:", gpu_x1.device, gpu_x1)

----------------------------------------
a.device: /job:localhost/replica:0/task:0/device:CPU:0 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>
b.device: /job:localhost/replica:0/task:0/device:GPU:0 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=10.0>
----------------------------------------
x1.device: /job:localhost/replica:0/task:0/device:CPU:0 tf.Tensor(100, shape=(), dtype=int32)
x2.device: /job:localhost/replica:0/task:0/device:CPU:0 tf.Tensor(1000.0, shape=(), dtype=float32)
----------------------------------------
ax1.device: /job:localhost/replica:0/task:0/device:GPU:0 tf.Tensor(101, shape=(), dtype=int32)
bx2.device: /job:localhost/replica:0/task:0/device:GPU:0 tf.Tensor(1010.0, shape=(), dtype=float32)
----------------------------------------
gpu_a.device: /job:localhost/replica:0/task:0/device:GPU:0 tf.Tensor(1, shape=(), dtype=int32)
gpu_x1.device: /job:localhost/replica:0/task:0/device:GPU:0 tf.Tensor(100, shape=(), dtype=int32)


# 實戰 
#使用TF裡提供類似 numpy 的功能去生成數據

In [8]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.system("cls")

import tensorflow as tf
import numpy as np

a = np.ones(12)
print(a)
a = tf.convert_to_tensor(a)
print(a)

a = tf.zeros(12)
print(a)

a = tf.zeros([4,3])
print(a)

a = tf.zeros([4,6,3])
print(a)

b = tf.zeros_like(a)
print(b)

a = tf.ones(12)
print(a)

a = tf.ones_like(b)
print(a)

a = tf.fill([3,2], 10.)
print(a)

a = tf.random.normal([12])
print(a)

a = tf.random.normal([4,3])
print(a)

a = tf.random.truncated_normal([3,2])
print(a)

a = tf.random.uniform([4,3], minval=0, maxval=10)
print(a)

a = tf.random.uniform([12], minval=0, maxval=10, dtype=tf.int32)
print(a)

a = tf.range([12], dtype=tf.int32)
print(a)
b = tf.random.shuffle(a)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(12,), dtype=float64)
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(12,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(4, 6, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(4, 6, 3), dtype

# 實戰 MSE 均方誤差函數
Mean-Square Error 預測值和實際觀測值間差的平方的均值。它只考慮誤差的平均大小，不考慮其方向。但由於經過平方，與真實值偏離較多的預測值會比偏離較少的預測值受到更為嚴重的懲罰。再加上 MSE 的數學特性很好，這使得計算梯度變得更容易。

In [9]:
import tensorflow as tf

rows = 1
out = tf.random.uniform([rows,10])
print("out:", out)
print("預測值 :", tf.math.argmax(out, axis=1), "\n")

y = tf.range(rows)
print("y:", y, "\n")

y = tf.one_hot(y, depth=10)
print("y_one_hot:", y, "\n")

loss = tf.keras.losses.mse(y, out)
print("row loss", loss, "\n")

loss = tf.reduce_mean(loss)
print("總體損失：", loss, "\n")

out: tf.Tensor(
[[0.14009607 0.5813856  0.2963065  0.550755   0.00407755 0.8130747
  0.822317   0.91029155 0.14059007 0.3313347 ]], shape=(1, 10), dtype=float32)
預測值 : tf.Tensor([7], shape=(1,), dtype=int64) 

y: tf.Tensor([0], shape=(1,), dtype=int32) 

y_one_hot: tf.Tensor([[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(1, 10), dtype=float32) 

row loss tf.Tensor([0.3764064], shape=(1,), dtype=float32) 

總體損失： tf.Tensor(0.3764064, shape=(), dtype=float32) 



全連接層Dense的參數

In [10]:
import tensorflow as tf

###################################################
# Dense: y=wx+b
rows = 1
net = tf.keras.layers.Dense(1) # 一個隱藏層，一個神經元
net.build((rows, 1)) # 訓練數據有一個特徵
print("net.w:", net.kernel) # 參數個數
print("net.b:", net.bias) # 和Dense數一樣

"""
"""

net.w: <tf.Variable 'kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.75629675]], dtype=float32)>
net.b: <tf.Variable 'bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>


'\n'

# 使用tf.reshape變換矩陣維度

In [11]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.system("cls")

import tensorflow as tf
import numpy as np

# 10張彩色圖片
a = tf.random.normal([10,28,28,3])
print(a)
print(a.shape) # 形狀
print(a.ndim)  # 維度

b = tf.reshape(a, [10, 784, 3])
print(b)
print(b.shape) # 形狀
print(b.ndim)  # 維度

c = tf.reshape(a, [10, -1, 3])
print(c)
print(c.shape) # 形狀
print(c.ndim)  # 維度

d = tf.reshape(a, [10, 784*3])
print(d)
print(d.shape) # 形狀
print(d.ndim)  # 維度

e = tf.reshape(a, [10, -1])
print(e)
print(e.shape) # 形狀
print(e.ndim)  # 維度

tf.Tensor(
[[[[-1.2976266   1.0493125   2.4988413 ]
   [-0.48153225  0.5237023   0.13084842]
   [-0.5991906  -0.9856748   0.6271027 ]
   ...
   [ 0.5296756  -0.02015255 -1.2647895 ]
   [-1.4745288  -0.86741513  0.8345732 ]
   [ 0.985634    2.210447    0.9058883 ]]

  [[ 2.304848   -0.27842227 -0.99408656]
   [ 0.4656547  -0.723117   -2.0518157 ]
   [ 0.02537764 -0.06615476 -0.2692781 ]
   ...
   [ 0.18121251 -0.4204738   0.5780772 ]
   [-2.0385966  -2.0466871  -1.2649981 ]
   [ 1.2064506   0.7013227  -0.2841767 ]]

  [[-0.7393596   1.991427   -0.34182674]
   [ 0.94537354 -1.4967086  -0.86313945]
   [-0.6400768  -0.7795642  -1.3626161 ]
   ...
   [ 1.3137254   0.0210819   1.586144  ]
   [-0.7529873   0.00639919  1.5718044 ]
   [-0.8656518   1.2482328  -1.56094   ]]

  ...

  [[ 0.22454612 -1.450773    0.98730165]
   [-0.8630083   0.30250722 -0.5197593 ]
   [ 0.9128744  -0.959481    0.09947037]
   ...
   [ 0.19110349 -0.860703    1.7542849 ]
   [-0.6545508  -0.19926694  1.3839276 ]
   [-